on: [push]

jobs:
  build_job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        type: [native, emscripten]
        exclude:
        - os: windows-latest
          type: emscripten
        - os: macos-latest
          type: emscripten
    name: Build
    steps:
    - name: Build step
      id: build
      uses: nicozink/github-build-actions@master
      with:
        who-to-greet: 'Mona the Octocat'
        os: matrix.os
        type: matrix.type
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}, running ${{ matrix.type }} on ${{ steps.hello.outputs.os }}"
